# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.11.3
_src_path: gh:algorandfoundation/algokit-beaker-default-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: co.rodolphe@gmail.com
author_name: CoffiRodolpheSegbedji
contract_name: dapp_nft_smart_contract
deployment_language: python
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
preset_name: starter
project_name: backend
use_python_black: true
use_python_pytest: true

